[package]
name = "generate"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
prettyplease = "0.2.15"
proc-macro2 = "1.0.71"
quote = "1.0.33"
rustdoc-types = "0.24.0"
serde = "1.0.193"
serde_json = "1.0.108"
syn = "2.0.43"
